### ISSUE TITLE
数据集开源情况

### ISSUE THREAD

**Issue by liuzengyun** [beyondliberty/DINs#1]
Hi，请问数据集还开源嘛

**Comment by cxchen123** [comment]
您好，请问完整的数据集如何获取

**Comment by liuzengyun** [comment]
> 您好，请问完整的数据集如何获取

作者跑路了  获取不了一点

**Comment by beyondliberty** [comment]
> > 您好，请问完整的数据集如何获取
> 
> 作者跑路了 获取不了一点

对，我是跑路了，因为毕业了。工作上的事情让我没有时间做最后的数据整理，拖到了现在。因为谷歌网盘空间的问题，只有mask部分数据是完整的，voc只上传没有增广的部分。

**Comment by liuzengyun** [comment]
> > > 您好，请问完整的数据集如何获取
> > 
> > 作者跑路了 获取不了一点
> 
> 对，我是跑路了，因为毕业了。工作上的事情让我没有时间做最后的数据整理，拖到了现在。因为谷歌网盘空间的问题，只有mask部分数据是完整的，voc只上传没有增广的部分。

感谢！哥们工作顺利！！

**Comment by liuzengyun** [comment]
> > > 您好，请问完整的数据集如何获取
> > 
> > 
> > 作者跑路了 获取不了一点
> 
> 对，我是跑路了，因为毕业了。工作上的事情让我没有时间做最后的数据整理，拖到了现在。因为谷歌网盘空间的问题，只有mask部分数据是完整的，voc只上传没有增广的部分。

您好，你的谷歌云盘链接设置了访问权限，请问可以开放下载嘛？

**Comment by beyondliberty** [comment]
我已经更新了权限

**Comment by beyondliberty** [comment]
> > > > 您好，请问完整的数据集如何获取
> > > 
> > > 
> > > 作者跑路了 获取不了一点
> > 
> > 
> > 对，我是跑路了，因为毕业了。工作上的事情让我没有时间做最后的数据整理，拖到了现在。因为谷歌网盘空间的问题，只有mask部分数据是完整的，voc只上传没有增广的部分。
> 
> 感谢！哥们工作顺利！！

我已经更新了权限
